### ISSUE TITLE
사용법에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by knightpop** [monoless/xe-oauth-server#1]
안녕하세요 개발자 센터를 한번 사용해보려고 하는데,

앱을 어디서 등록하는 방법이 궁금합니다.

좋은 모듈 만들어 주셔서 감사합니다.

**Comment by qlazzarus** [comment]
안녕하세요. 먼저 좋게 봐주셔서 감사합니다.
앱 설치 후 개인 메뉴에서 `내 어플리케이션 목록`메뉴를 선택합니다
/index.php?act=dispDevcenterGrantApp

그 이후 `내 어플리케이션 등록` 메뉴를 통해서 앱 등록이 가능합니다.
/index.php?act=dispDevcenterRegisterApp

감사합니다.
